TEST_RUN_EFFECTIVE_BATCH_SIZE = 8
TEST_RUN_EPOCHS = 2
TEST_RUN_UPDATES_PER_EPOCH = 3
TEST_RUN_UPDATES = TEST_RUN_EPOCHS * TEST_RUN_UPDATES_PER_EPOCH
TEST_RUN_SAMPLES = TEST_RUN_UPDATES * TEST_RUN_EFFECTIVE_BATCH_SIZE
